CREATE TABLE IF NOT EXISTS `document_action_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `document_id` int(11) NOT NULL,
  `sender_branch_id` int(10) unsigned DEFAULT NULL,
  `recipient_branch_id` int(10) unsigned DEFAULT NULL,
  `route_id` int(11) NOT NULL,
  `sender_user_id` int(11) NOT NULL,
  `sender_section_id` int(11) NOT NULL,
  `recipient_user_id` int(11) NOT NULL,
  `recipient_section_id` int(11) NOT NULL,
  `request_notes` text DEFAULT NULL,
  `task_status` enum('PENDING_RECEIVE','IN_PROGRESS','SIGNED','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING_RECEIVE',
  `received_at` datetime DEFAULT NULL,
  `acted_at` datetime DEFAULT NULL,
  `acted_by_user_id` int(11) DEFAULT NULL,
  `decision_notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_dar_document_sender_status` (`document_id`, `sender_user_id`, `task_status`),
  KEY `idx_dar_document_sender_branch_status` (`document_id`, `sender_branch_id`, `task_status`),
  KEY `idx_dar_document_recipient_status` (`document_id`, `recipient_user_id`, `task_status`),
  KEY `idx_dar_document_recipient_branch_status` (`document_id`, `recipient_branch_id`, `task_status`),
  KEY `idx_dar_route` (`route_id`),
  CONSTRAINT `fk_dar_document` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_dar_route` FOREIGN KEY (`route_id`) REFERENCES `routes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_dar_sender_branch` FOREIGN KEY (`sender_branch_id`) REFERENCES `document_branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_dar_recipient_branch` FOREIGN KEY (`recipient_branch_id`) REFERENCES `document_branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_dar_acted_by_user` FOREIGN KEY (`acted_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
