CREATE TABLE IF NOT EXISTS `attachment_forward_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `document_id` int(11) NOT NULL,
  `sender_branch_id` int(10) UNSIGNED NOT NULL,
  `recipient_branch_id` int(10) UNSIGNED NOT NULL,
  `route_id` int(11) NOT NULL,
  `source_attachment_id` int(11) NOT NULL,
  `forwarded_attachment_id` int(11) NOT NULL,
  `sender_user_id` int(11) NOT NULL,
  `sender_section_id` int(11) NOT NULL,
  `recipient_user_id` int(11) NOT NULL,
  `recipient_section_id` int(11) NOT NULL,
  `batch_id` varchar(64) NOT NULL,
  `task_status` enum('PENDING_RECEIVE','IN_PROGRESS','DONE','CANCELLED') NOT NULL DEFAULT 'PENDING_RECEIVE',
  `received_at` datetime DEFAULT NULL,
  `done_at` datetime DEFAULT NULL,
  `done_by_user_id` int(11) DEFAULT NULL,
  `done_remarks` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_aft_document_sender_status` (`document_id`, `sender_branch_id`, `task_status`),
  KEY `idx_aft_document_recipient_status` (`document_id`, `recipient_branch_id`, `task_status`),
  KEY `idx_aft_route` (`route_id`),
  KEY `idx_aft_batch` (`batch_id`),
  CONSTRAINT `fk_aft_document` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aft_sender_branch` FOREIGN KEY (`sender_branch_id`) REFERENCES `document_branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aft_recipient_branch` FOREIGN KEY (`recipient_branch_id`) REFERENCES `document_branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aft_route` FOREIGN KEY (`route_id`) REFERENCES `routes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aft_source_attachment` FOREIGN KEY (`source_attachment_id`) REFERENCES `document_attachments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aft_forwarded_attachment` FOREIGN KEY (`forwarded_attachment_id`) REFERENCES `document_attachments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
