CREATE TABLE IF NOT EXISTS tms_task_types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(150) NOT NULL,
  scope_code VARCHAR(32) NULL,
  workflow_rule VARCHAR(32) NOT NULL DEFAULT 'manual',
  assignment_role_label VARCHAR(64) NOT NULL DEFAULT 'Assigned To',
  reference_label VARCHAR(64) NULL,
  allow_multi_assignees TINYINT(1) NOT NULL DEFAULT 0,
  show_date_surveyed TINYINT(1) NOT NULL DEFAULT 0,
  show_date_received TINYINT(1) NOT NULL DEFAULT 0,
  show_date_started TINYINT(1) NOT NULL DEFAULT 0,
  show_target_completion TINYINT(1) NOT NULL DEFAULT 0,
  show_progress TINYINT(1) NOT NULL DEFAULT 0,
  show_reference_code TINYINT(1) NOT NULL DEFAULT 0,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tms_task_types_code (code),
  KEY idx_tms_task_types_scope (scope_code),
  KEY idx_tms_task_types_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_user_profiles (
  user_id INT NOT NULL,
  scope_code VARCHAR(32) NULL,
  can_manage_all_tasks TINYINT(1) NOT NULL DEFAULT 0,
  can_edit_protected_fields TINYINT(1) NOT NULL DEFAULT 0,
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  KEY idx_tms_user_profiles_scope (scope_code),
  CONSTRAINT fk_tms_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_type_id INT UNSIGNED NOT NULL,
  project_id INT UNSIGNED NULL,
  document_id INT NULL,
  created_by_user_id INT NOT NULL,
  updated_by_user_id INT NULL,
  owner_user_id INT NULL,
  division_id INT NULL,
  section_id INT NULL,
  scope_code VARCHAR(32) NULL,
  project_code VARCHAR(100) NOT NULL,
  project_title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  deo VARCHAR(150) NULL,
  lgu VARCHAR(150) NULL,
  assignee_display VARCHAR(255) NULL,
  date_surveyed DATE NULL,
  date_received DATE NULL,
  date_started DATE NULL,
  target_completion DATE NULL,
  remaining_workdays INT NULL,
  progress_percent DECIMAL(5,2) NULL,
  status_label VARCHAR(80) NOT NULL DEFAULT 'Ongoing',
  reference_code VARCHAR(150) NULL,
  remarks TEXT NULL,
  completed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tms_tasks_type (task_type_id),
  KEY idx_tms_tasks_project (project_id),
  KEY idx_tms_tasks_document (document_id),
  KEY idx_tms_tasks_owner (owner_user_id),
  KEY idx_tms_tasks_creator (created_by_user_id),
  KEY idx_tms_tasks_division (division_id),
  KEY idx_tms_tasks_scope (scope_code),
  KEY idx_tms_tasks_status (status_label),
  KEY idx_tms_tasks_target_completion (target_completion),
  KEY idx_tms_tasks_updated (updated_at),
  CONSTRAINT fk_tms_tasks_type FOREIGN KEY (task_type_id) REFERENCES tms_task_types(id),
  CONSTRAINT fk_tms_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_tms_tasks_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_tms_tasks_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_tms_tasks_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_tms_tasks_division FOREIGN KEY (division_id) REFERENCES divisions(id) ON DELETE SET NULL,
  CONSTRAINT fk_tms_tasks_section FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE SET NULL,
  CONSTRAINT fk_tms_tasks_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_task_assignees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  user_id INT NULL,
  display_name VARCHAR(150) NOT NULL,
  assignment_role VARCHAR(32) NOT NULL DEFAULT 'assignee',
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tms_task_assignees_task_slot (task_id, assignment_role, sort_order),
  KEY idx_tms_task_assignees_user (user_id),
  KEY idx_tms_task_assignees_primary (task_id, is_primary),
  CONSTRAINT fk_tms_task_assignees_task FOREIGN KEY (task_id) REFERENCES tms_tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_tms_task_assignees_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_task_activity (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  actor_user_id INT NULL,
  action VARCHAR(32) NOT NULL,
  message VARCHAR(255) NULL,
  old_values_json LONGTEXT NULL,
  new_values_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tms_task_activity_task (task_id),
  KEY idx_tms_task_activity_actor (actor_user_id),
  KEY idx_tms_task_activity_created (created_at),
  CONSTRAINT fk_tms_task_activity_task FOREIGN KEY (task_id) REFERENCES tms_tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_tms_task_activity_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_import_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_label VARCHAR(120) NOT NULL,
  source_filename VARCHAR(255) NULL,
  imported_by_user_id INT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tms_import_batches_user (imported_by_user_id),
  CONSTRAINT fk_tms_import_batches_user FOREIGN KEY (imported_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_import_rows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  task_id BIGINT UNSIGNED NULL,
  task_type_code VARCHAR(64) NULL,
  legacy_key VARCHAR(120) NULL,
  raw_payload_json LONGTEXT NULL,
  import_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  import_message VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tms_import_rows_batch (batch_id),
  KEY idx_tms_import_rows_task (task_id),
  CONSTRAINT fk_tms_import_rows_batch FOREIGN KEY (batch_id) REFERENCES tms_import_batches(id) ON DELETE CASCADE,
  CONSTRAINT fk_tms_import_rows_task FOREIGN KEY (task_id) REFERENCES tms_tasks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tms_task_types (
  code,
  name,
  scope_code,
  workflow_rule,
  assignment_role_label,
  reference_label,
  allow_multi_assignees,
  show_date_surveyed,
  show_date_received,
  show_date_started,
  show_target_completion,
  show_progress,
  show_reference_code,
  sort_order,
  is_active
) VALUES
  ('prepared_daed', 'Prepared DAED/DED Plan', 'design', 'progress_remaining', 'Designer/s', NULL, 1, 1, 1, 1, 1, 1, 0, 10, 1),
  ('reviewed_daed', 'Reviewed DAED/DED Plan', 'design', 'progress_remaining', 'Reviewer/s', NULL, 1, 0, 1, 0, 1, 1, 0, 20, 1),
  ('prepared_conceptual', 'Prepared Conceptual Plan', 'design', 'progress_remaining', 'Concept Designer/s', NULL, 1, 0, 1, 0, 1, 1, 0, 30, 1),
  ('reviewed_conceptual', 'Reviewed Conceptual Plan', 'design', 'progress_remaining', 'Concept Reviewer/s', NULL, 1, 0, 1, 0, 1, 1, 0, 40, 1),
  ('engineering_survey', 'Engineering Survey', 'survey', 'status_from_reference', 'Surveyor', 'BTOR', 1, 1, 0, 0, 0, 0, 1, 50, 1),
  ('as_staked_survey', 'As-Staked Survey', 'survey', 'status_from_reference', 'Surveyor', 'BTOR', 1, 1, 0, 0, 0, 0, 1, 60, 1),
  ('reviewed_as_staked_plan', 'Reviewed As-Staked Plan', 'design', 'progress_remaining', 'Reviewer/s', NULL, 1, 1, 1, 1, 1, 1, 0, 70, 1),
  ('reviewed_drawing', 'Reviewed Drawings', 'design', 'progress_remaining', 'Reviewer/s', NULL, 1, 0, 1, 1, 1, 1, 0, 80, 1),
  ('field_report', 'Field Inspection/Investigation Reports', 'survey', 'status_from_reference', 'Assigned To', 'Reports', 1, 1, 0, 0, 0, 0, 1, 90, 1),
  ('sdri', 'SDRI', 'survey', 'status_from_reference', 'Assigned To', 'Transmittal Code', 1, 0, 1, 1, 1, 0, 1, 100, 1),
  ('standard_plan', 'Standard Plan', 'design', 'status_from_reference', 'Assigned To', 'Transmittal Code', 1, 0, 1, 1, 1, 0, 1, 110, 1),
  ('other_report', 'Other Reports', 'survey', 'status_from_reference', 'Assigned To', 'BTOR', 1, 0, 1, 1, 1, 0, 1, 120, 1),
  ('misc_documents', 'Miscellaneous Documents', 'design', 'status_from_reference', 'Assigned To', 'Transmittal Code', 1, 0, 1, 1, 1, 0, 1, 130, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  scope_code = VALUES(scope_code),
  workflow_rule = VALUES(workflow_rule),
  assignment_role_label = VALUES(assignment_role_label),
  reference_label = VALUES(reference_label),
  allow_multi_assignees = VALUES(allow_multi_assignees),
  show_date_surveyed = VALUES(show_date_surveyed),
  show_date_received = VALUES(show_date_received),
  show_date_started = VALUES(show_date_started),
  show_target_completion = VALUES(show_target_completion),
  show_progress = VALUES(show_progress),
  show_reference_code = VALUES(show_reference_code),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);
