import type { OrgChartBootstrap } from '../types/org'

export const mockBootstrap: OrgChartBootstrap = {
  rootDivision: {
    id: 1,
    name: 'Office of the Director',
    section_count: 1,
    user_count: 2,
    chief_office: {
      id: 10,
      name: 'Director Office',
      member_count: 0,
      users: [],
      leaders: [
        {
          id: 101,
          full_name: 'Atty. Pangalian M. Balindong',
          email: 'director@mpw.local',
          authority_role: 'director',
          display_title: 'Director',
          official_title: 'Director',
          section_name: 'Director Office',
          section_id: 10,
          division_id: 1,
          division_name: 'Office of the Director',
          permanent: 1,
          is_leader: true,
          can_edit: false,
          can_assign_assistant: false,
          chief_assistant_names: '',
        },
      ],
      members: [],
      is_chief_office: true,
    },
    child_sections: [],
  },
  childDivisions: [
    {
      id: 2,
      name: 'Survey and Design Division',
      section_count: 3,
      user_count: 8,
      chief_office: {
        id: 21,
        name: 'Office of the Division Chief',
        member_count: 2,
        users: [],
        leaders: [
          {
            id: 201,
            full_name: 'Emraiza D. Mangacop',
            email: 'emraiza@mpw.local',
            authority_role: 'division_head',
            display_title: 'Division Chief',
            official_title: 'Division Chief',
            section_name: 'Office of the Division Chief',
            section_id: 21,
            division_id: 2,
            division_name: 'Survey and Design Division',
            permanent: 1,
            is_leader: true,
            can_edit: false,
            can_assign_assistant: true,
            assistant_candidates_json: JSON.stringify([
              {
                id: 205,
                full_name: 'Aira A. Arsolon',
                display_title: 'Administrative Officer',
                section_id: 23,
                section_name: 'Administrative Support',
                division_id: 2,
                division_name: 'Survey and Design Division',
              },
            ]),
            chief_assistant_user_ids: '205',
            chief_assistant_names: 'Aira A. Arsolon',
          },
        ],
        members: [
          {
            id: 202,
            full_name: 'Candido S. Radam, Jr.',
            email: 'candido@mpw.local',
            authority_role: 'staff',
            display_title: 'Engineering Aide',
            official_title: 'Engineering Aide',
            section_name: 'Office of the Division Chief',
            section_id: 21,
            division_id: 2,
            division_name: 'Survey and Design Division',
            permanent: 1,
            is_leader: false,
            can_edit: true,
            can_assign_assistant: false,
            show_presence: true,
            is_online: true,
          },
          {
            id: 203,
            full_name: 'Saida R. Akmad',
            email: 'saida@mpw.local',
            authority_role: 'staff',
            display_title: 'Technical Staff',
            official_title: 'Technical Staff',
            section_name: 'Office of the Division Chief',
            section_id: 21,
            division_id: 2,
            division_name: 'Survey and Design Division',
            permanent: 1,
            is_leader: false,
            can_edit: true,
            can_assign_assistant: false,
            show_presence: true,
            is_online: false,
          },
        ],
        is_chief_office: true,
      },
      child_sections: [
        {
          id: 22,
          name: 'Planning Section',
          member_count: 2,
          users: [],
          leaders: [
            {
              id: 204,
              full_name: 'Kenneth Marie Villamor',
              email: 'kenneth@mpw.local',
              authority_role: 'section_head',
              display_title: 'Section Chief',
              official_title: 'Section Chief',
              section_name: 'Planning Section',
              section_id: 22,
              division_id: 2,
              division_name: 'Survey and Design Division',
              permanent: 1,
              is_leader: true,
              can_edit: false,
              can_assign_assistant: true,
              assistant_candidates_json: JSON.stringify([]),
              chief_assistant_user_ids: '',
              chief_assistant_names: '',
            },
          ],
          members: [
            {
              id: 205,
              full_name: 'Aira A. Arsolon',
              email: 'aira@mpw.local',
              authority_role: 'staff',
              display_title: 'Administrative Officer',
              official_title: 'Administrative Officer',
              section_name: 'Planning Section',
              section_id: 22,
              division_id: 2,
              division_name: 'Survey and Design Division',
              permanent: 1,
              is_leader: false,
              can_edit: true,
              can_assign_assistant: false,
            },
          ],
        },
      ],
    },
  ],
  spotlightDivision: null,
  divisions: [],
  assignableRoles: {
    director: 'Director',
    division_head: 'Division Chief',
    division_assistant: 'Division Assistant',
    section_head: 'Section Head',
    staff: 'Staff',
  },
  canManageOrg: true,
  viewerDivisionId: 2,
  stats: {
    activeDivisions: 1,
    activeUsers: 10,
    totalSections: 4,
  },
  copy: {
    eyebrow: '2026 Org Atlas',
    title: 'Technical Services, refined.',
    subtitle: 'Delivering precision in public works',
  },
}

mockBootstrap.spotlightDivision = mockBootstrap.childDivisions[0]
mockBootstrap.divisions = [mockBootstrap.rootDivision!, ...mockBootstrap.childDivisions]
