<?php
declare(strict_types=1);

require __DIR__ . "/../includes/bootstrap.php";
require_once __DIR__ . "/../core/division_tracking.php";
require_once __DIR__ . "/../core/DivisionTrackingSlip.php";
require_login();

header("Content-Type: application/json");

if ($_SERVER["REQUEST_METHOD"] !== "POST") {
  http_response_code(405);
  echo json_encode(["ok" => false, "error" => "Method not allowed"]);
  exit;
}

require_csrf();

$docId = (int)($_POST["document_id"] ?? 0);
if ($docId <= 0) {
  http_response_code(400);
  echo json_encode(["ok" => false, "error" => "Bad document id"]);
  exit;
}

$identity = effective_document_identity($conn);
$actualUserId = (int)($identity["actual_user_id"] ?? ($_SESSION["user_id"] ?? 0));
$actualUserFullName = trim((string)($identity["actual_full_name"] ?? ($_SESSION["full_name"] ?? "")));
$userId = (int)($identity["effective_user_id"] ?? ($_SESSION["user_id"] ?? 0));
$mySectionId = (int)($identity["effective_section_id"] ?? ($_SESSION["section_id"] ?? 0));
if ($mySectionId <= 0 || !can_view_document($conn, $docId)) {
  http_response_code(403);
  echo json_encode(["ok" => false, "error" => "Access denied"]);
  exit;
}

$myDivision = get_user_division_meta($conn, $mySectionId);
if (!is_array($myDivision) || !is_supported_division_tracking_code($myDivision['code'] ?? '')) {
  http_response_code(403);
  echo json_encode(["ok" => false, "error" => "Division tracking slip is not available for your division"]);
  exit;
}
$divisionId = (int)$myDivision['id'];
$divisionCode = strtoupper(trim((string)$myDivision['code']));
$divisionName = (string)$myDivision['name'];

$stmt = $conn->prepare("
  SELECT
    d.id,
    d.tracking_no,
    d.requester,
    d.document_date,
    d.deadline_at,
    d.subject,
    d.content_type,
    d.origin_section_id,
    d.current_holder_section_id,
    d.created_by_user_id,
    COALESCE(NULLIF(TRIM(u.full_name), ''), '') AS created_by_name,
    EXISTS (
      SELECT 1
      FROM sections s_holder
      WHERE s_holder.id = d.current_holder_section_id
        AND s_holder.division_id = ?
    ) AS has_holder_in_my_division,
    EXISTS (
      SELECT 1
      FROM document_branches b_holder
      JOIN sections s_branch ON s_branch.id = b_holder.current_assignee_section_id
      WHERE b_holder.document_id = d.id
        AND b_holder.branch_status = 'ACTIVE'
        AND b_holder.is_reference = 0
        AND s_branch.division_id = ?
    ) AS has_branch_holder_for_me
  FROM documents d
  LEFT JOIN users u ON u.id = d.created_by_user_id
  WHERE d.id = ?
  LIMIT 1
");
$stmt->bind_param('iii', $divisionId, $divisionId, $docId);
$stmt->execute();
$doc = $stmt->get_result()->fetch_assoc();
if (!$doc) {
  http_response_code(404);
  echo json_encode(["ok" => false, "error" => "Document not found"]);
  exit;
}

$canRegenerate = (
  (int)($doc['has_holder_in_my_division'] ?? 0) === 1
  || (int)($doc['has_branch_holder_for_me'] ?? 0) === 1
);

if (!$canRegenerate) {
  http_response_code(403);
  echo json_encode(["ok" => false, "error" => "Division tracking slip can only be generated by the current holder division"]);
  exit;
}

function division_slip_original_received_meta(mysqli $conn, int $documentId, string $divisionCode): array
{
  $divisionCode = strtoupper(trim($divisionCode));
  $stmt = $conn->prepare("
    SELECT payload_json
    FROM document_events
    WHERE document_id = ?
      AND event_type = 'updated'
      AND payload_json LIKE '%division_tracking_slip_generated%'
    ORDER BY id ASC
  ");
  $stmt->bind_param('i', $documentId);
  $stmt->execute();
  $rows = $stmt->get_result()->fetch_all(MYSQLI_ASSOC) ?: [];

  foreach ($rows as $row) {
    $payload = json_decode((string)($row['payload_json'] ?? ''), true);
    if (!is_array($payload)) {
      continue;
    }
    if (trim((string)($payload['kind'] ?? '')) !== 'division_tracking_slip_generated') {
      continue;
    }
    $payloadDivision = strtoupper(trim((string)($payload['division_code'] ?? '')));
    if ($divisionCode !== '' && $payloadDivision !== '' && $payloadDivision !== $divisionCode) {
      continue;
    }

    return [
      'received_by' => trim((string)($payload['received_by_name'] ?? '')),
      'received_datetime' => trim((string)($payload['received_datetime'] ?? '')),
      'assistant_user_id' => (int)($payload['assistant_actual_user_id'] ?? 0),
    ];
  }

  return ['received_by' => '', 'received_datetime' => '', 'assistant_user_id' => 0];
}

function division_slip_assistant_name_for_principal(mysqli $conn, int $principalUserId): string
{
  if ($principalUserId <= 0) {
    return '';
  }

  if (function_exists('assistant_assignments_table_ready') && assistant_assignments_table_ready($conn)) {
    $stmt = $conn->prepare("
      SELECT COALESCE(NULLIF(TRIM(u.full_name), ''), '') AS assistant_name
      FROM principal_assistants pa
      JOIN users u ON u.id = pa.assistant_user_id
      WHERE pa.principal_user_id = ?
        AND u.is_active = 1
      ORDER BY u.full_name ASC, u.id ASC
      LIMIT 1
    ");
    $stmt->bind_param('i', $principalUserId);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $name = trim((string)($row['assistant_name'] ?? ''));
    if ($name !== '') {
      return $name;
    }
  }

  if (db_column_exists($conn, 'users', 'chief_assistant_user_id')) {
    $stmt = $conn->prepare("
      SELECT COALESCE(NULLIF(TRIM(a.full_name), ''), '') AS assistant_name
      FROM users p
      JOIN users a ON a.id = p.chief_assistant_user_id
      WHERE p.id = ?
        AND a.is_active = 1
      LIMIT 1
    ");
    $stmt->bind_param('i', $principalUserId);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    return trim((string)($row['assistant_name'] ?? ''));
  }

  return '';
}

function division_slip_format_received_datetime_input(?string $raw): string
{
  $raw = trim((string)$raw);
  if ($raw === '') {
    return '';
  }

  $tz = new DateTimeZone('Asia/Manila');
  $formats = ['Y-m-d\TH:i', 'Y-m-d H:i:s', 'Y-m-d H:i'];
  foreach ($formats as $format) {
    $dt = DateTime::createFromFormat($format, $raw, $tz);
    if ($dt instanceof DateTime) {
      $errors = DateTime::getLastErrors();
      if ($errors === false || (((int)$errors['warning_count'] === 0) && ((int)$errors['error_count'] === 0))) {
        return $dt->format('m/d/y g:ia');
      }
    }
  }

  return '';
}

function division_slip_resolve_received_defaults(mysqli $conn, int $documentId, int $divisionId, array $identity, array $doc): array
{
  $assistantMode = (bool)($identity['assistant_mode'] ?? false);
  $actualFullName = trim((string)($identity['actual_full_name'] ?? ''));
  $createdByUserId = (int)($doc['created_by_user_id'] ?? 0);
  $createdByName = trim((string)($doc['created_by_name'] ?? ''));

  $latestDivisionReceipt = get_latest_division_route_receipt_meta($conn, $documentId, $divisionId);
  $defaultReceivedBy = trim((string)($latestDivisionReceipt['received_by'] ?? ''));
  $defaultReceivedAtRaw = trim((string)($latestDivisionReceipt['received_at'] ?? ''));

  if ($assistantMode && $actualFullName !== '') {
    $defaultReceivedBy = $actualFullName;
  }

  if ($defaultReceivedBy === '') {
    $creatorAssistant = division_slip_assistant_name_for_principal($conn, $createdByUserId);
    if ($creatorAssistant !== '') {
      $defaultReceivedBy = $creatorAssistant;
    }
  }

  if ($defaultReceivedBy === '') {
    $defaultReceivedBy = $createdByName !== '' ? $createdByName : $actualFullName;
  }

  if ($defaultReceivedAtRaw === '') {
    $defaultReceivedAtRaw = (new DateTimeImmutable('now', new DateTimeZone('Asia/Manila')))->format('Y-m-d H:i:s');
  }

  return [
    'received_by' => $defaultReceivedBy,
    'received_at_raw' => $defaultReceivedAtRaw,
    'received_at_display' => division_slip_format_received_datetime_input($defaultReceivedAtRaw),
  ];
}

$trackingRow = get_document_division_tracking($conn, $docId, $divisionId);
$submittedTrackingNo = strtoupper(trim((string)($_POST['division_tracking_no'] ?? '')));
$submittedReceivedBy = trim((string)($_POST['received_by_name'] ?? ''));
$submittedReceivedDatetime = trim((string)($_POST['received_datetime'] ?? ''));
$allowDuplicateTrackingNo = (int)($_POST['allow_duplicate_tracking_no'] ?? 0) === 1;
$originDivisionMeta = get_user_division_meta($conn, (int)($doc['origin_section_id'] ?? 0));
$originDivisionId = (int)($originDivisionMeta['id'] ?? 0);
$isCrossDivisionDocument = $originDivisionId > 0 && $originDivisionId !== $divisionId;
$canForceDuplicateTrackingNo = $isCrossDivisionDocument && $allowDuplicateTrackingNo;

try {
  if ($submittedTrackingNo !== '') {
    upsert_document_division_tracking($conn, $docId, $divisionId, $submittedTrackingNo, $actualUserId, true, $canForceDuplicateTrackingNo);
  } elseif (!$trackingRow) {
    $defaultNo = preview_next_division_tracking_number($conn, $divisionId, new DateTimeImmutable('now', new DateTimeZone('Asia/Manila')), 'INCOMING');
    upsert_document_division_tracking($conn, $docId, $divisionId, $defaultNo, $actualUserId, false);
  }
} catch (Throwable $e) {
  http_response_code(400);
  echo json_encode(["ok" => false, "error" => $e->getMessage()]);
  exit;
}

$trackingRow = get_document_division_tracking($conn, $docId, $divisionId);
if (!$trackingRow) {
  http_response_code(500);
  echo json_encode(["ok" => false, "error" => "Unable to resolve division tracking number"]);
  exit;
}
$trackingScope = normalize_division_tracking_scope((string)($trackingRow['tracking_scope'] ?? 'INCOMING'));

$originSectionId = (int)($doc['origin_section_id'] ?? 0);

$requester = trim((string)($doc['requester'] ?? ''));
$fromLabel = '';

if ($requester !== '') {
  $fromLabel = $requester;
} elseif ($originSectionId > 0) {
  $stmt = $conn->prepare("
    SELECT
      COALESCE(NULLIF(TRIM(s.name), ''), '') AS section_name,
      COALESCE(NULLIF(TRIM(d.name), ''), '') AS division_name
    FROM sections s
    JOIN divisions d ON d.id = s.division_id
    WHERE s.id = ?
    LIMIT 1
  ");
  $stmt->bind_param('i', $originSectionId);
  $stmt->execute();
  $r = $stmt->get_result()->fetch_assoc();

  if ($r) {
    $sectionName = trim((string)($r['section_name'] ?? ''));
    $divisionNameFromOrigin = trim((string)($r['division_name'] ?? ''));

    if ($divisionNameFromOrigin !== '' && $sectionName !== '') {
      $fromLabel = $divisionNameFromOrigin . ' / ' . $sectionName;
    } elseif ($divisionNameFromOrigin !== '') {
      $fromLabel = $divisionNameFromOrigin;
    } elseif ($sectionName !== '') {
      $fromLabel = $sectionName;
    }
  }
}

$receivedDefaults = division_slip_resolve_received_defaults($conn, $docId, $divisionId, $identity, $doc);
$receivedBy = (bool)($identity['assistant_mode'] ?? false)
  ? trim((string)($identity['actual_full_name'] ?? ''))
  : ($submittedReceivedBy !== ''
  ? $submittedReceivedBy
  : trim((string)($receivedDefaults['received_by'] ?? '')));
$receivedDT = division_slip_format_received_datetime_input($submittedReceivedDatetime);
if ($receivedDT === '') {
  $receivedDT = trim((string)($receivedDefaults['received_at_display'] ?? ''));
}
$initialReceiveAtRaw = $submittedReceivedDatetime !== ''
  ? str_replace('T', ' ', $submittedReceivedDatetime) . (strlen($submittedReceivedDatetime) === 16 ? ':00' : '')
  : trim((string)($receivedDefaults['received_at_raw'] ?? ''));
$originalSlipMeta = division_slip_original_received_meta($conn, $docId, $divisionCode);

$head = resolve_division_head($conn, $divisionId);
$flowRows = build_division_slip_flow_rows($conn, $docId, $divisionId, $receivedBy, [
  'initial_receive_name' => $receivedBy,
  'initial_receive_datetime' => $initialReceiveAtRaw,
  'only_division_outgoing' => true,
]);
$flowRows = ($originDivisionId > 0 && $originDivisionId !== $divisionId && count($flowRows) === 0)
  ? []
  : $flowRows;
$nameEntries = build_division_name_initial_entries($conn, $divisionId, (int)($head['id'] ?? 0));
$safeTracking = preg_replace('/[^A-Za-z0-9._-]+/', '_', (string)($doc['tracking_no'] ?? 'document')) ?: 'document';
$safeDivision = preg_replace('/[^A-Za-z0-9._-]+/', '_', $divisionCode) ?: 'DIVISION';

$baseDir = realpath(__DIR__ . "/../storage/attachments");
if ($baseDir === false) {
  $baseDir = __DIR__ . "/../storage/attachments";
  if (!is_dir($baseDir)) mkdir($baseDir, 0775, true);
}
$docDir = rtrim((string)$baseDir, "/\\") . "/doc_" . $docId;
if (!is_dir($docDir)) mkdir($docDir, 0775, true);

$storedName = $safeDivision . '_TRACKING_SLIP_' . $safeTracking . '_' . date('Ymd_His') . '.pdf';
$abs = $docDir . '/' . $storedName;
$rel = 'storage/attachments/doc_' . $docId . '/' . $storedName;

$note = division_tracking_attachment_note($divisionCode);
$supersededNote = $note . ':SUPERSEDED';
$hadExistingDivisionSlip = false;
$stmt = $conn->prepare("
  SELECT id
  FROM document_attachments
  WHERE document_id = ?
    AND is_deleted = 0
    AND (
      note = ?
      OR (? = 'PPD' AND note = 'AUTO:PPD_TRACKING_SLIP')
    )
  ORDER BY id DESC
  LIMIT 1
");
$stmt->bind_param('iss', $docId, $note, $divisionCode);
$stmt->execute();
$hadExistingDivisionSlip = (bool)$stmt->get_result()->fetch_assoc();

$stmt = $conn->prepare("
  UPDATE document_attachments
  SET note = ?, is_append = 0
  WHERE document_id = ?
    AND is_deleted = 0
    AND (
      note = ?
      OR (? = 'PPD' AND note = 'AUTO:PPD_TRACKING_SLIP')
    )
");
$stmt->bind_param('siss', $supersededNote, $docId, $note, $divisionCode);
$stmt->execute();

$qrToken = null;
$stmt = $conn->prepare("SELECT token FROM document_qr_tokens WHERE document_id = ? AND revoked_at IS NULL ORDER BY id DESC LIMIT 1");
$stmt->bind_param('i', $docId);
$stmt->execute();
$rowTok = $stmt->get_result()->fetch_assoc();
if ($rowTok && !empty($rowTok['token'])) {
  $qrToken = (string)$rowTok['token'];
} else {
  $qrToken = bin2hex(random_bytes(16));
  $stmt = $conn->prepare("INSERT INTO document_qr_tokens (document_id, token) VALUES (?, ?)");
  $stmt->bind_param('is', $docId, $qrToken);
  $stmt->execute();
}
$qrUrl = app_url(PUBLIC_PATH . '/qr.php?t=' . urlencode($qrToken));


DivisionTrackingSlip::generateA4([
  'mpw_tracking_no' => (string)($doc['tracking_no'] ?? ''),
  'division_tracking_no' => (string)$trackingRow['tracking_no'],
  'division_name' => $divisionName,
  'division_code' => $divisionCode,
  'from_label' => $fromLabel,
  'document_type' => (string)($doc['content_type'] ?? ''),
  'document_date' => (string)($doc['document_date'] ?? ''),
  'receipt_label' => division_tracking_receipt_label($trackingScope),
  'received_datetime_label' => division_tracking_received_datetime_label($trackingScope),
  'received_by' => $receivedBy,
  'received_datetime' => $receivedDT,
  'subject' => (string)($doc['subject'] ?? ''),
  'deadline_date' => trim((string)($doc['deadline_at'] ?? '')) !== '' ? (new DateTime((string)$doc['deadline_at'], new DateTimeZone('Asia/Manila')))->format('m/d/Y') : '',
  'deadline_time' => trim((string)($doc['deadline_at'] ?? '')) !== '' ? (new DateTime((string)$doc['deadline_at'], new DateTimeZone('Asia/Manila')))->format('g:i A') : '',
  'qr_url' => $qrUrl,
  'logo_left_abs' => realpath(__DIR__ . '/../assets/mpwlogo1.png') ?: '',
  'logo_right_abs' => realpath(__DIR__ . '/../assets/ocmlogo.png') ?: '',
  'signatory_name' => (string)($head['full_name'] ?? ''),
  'signatory_title' => 'Chief' . ($divisionName !== '' ? ', ' . $divisionName : ''),
  'flow_rows' => $flowRows,
  'name_entries' => $nameEntries,
], $abs);

$size = (int)@filesize($abs);
if ($size <= 0) {
  http_response_code(500);
  echo json_encode(["ok" => false, "error" => "Failed to generate PDF"]);
  exit;
}
if ($size > attachment_max_bytes()) {
  @unlink($abs);
  http_response_code(400);
  echo json_encode(["ok" => false, "error" => "Generated PDF is too large (max " . attachment_max_mb_label() . ")"]);
  exit;
}

$mime = 'application/pdf';
$orig = $storedName;
$stmt = $conn->prepare("INSERT INTO document_attachments
  (document_id, original_name, stored_name, stored_path, mime, size_bytes, note, is_append, uploaded_by_user_id, uploaded_by_section_id)
  VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?)");
$stmt->bind_param('issssisii', $docId, $orig, $storedName, $rel, $mime, $size, $note, $actualUserId, $mySectionId);
$stmt->execute();
$attId = (int)$conn->insert_id;

$payload = json_encode([
  'kind' => 'division_tracking_slip_generated',
  'attachment_id' => $attId,
  'file' => $orig,
  'division_code' => $divisionCode,
  'slip_direction' => strtolower($trackingScope),
  'received_by_name' => $receivedBy,
  'received_datetime' => $receivedDT,
  'assistant_actual_user_id' => (int)($originalSlipMeta['assistant_user_id'] ?? 0) ?: null,
  'acting_principal_user_id' => ($userId > 0 && $userId !== $actualUserId) ? $userId : null,
  'acting_principal_name' => ($userId > 0 && $userId !== $actualUserId) ? (string)($identity['acting_principal_name'] ?? '') : '',
  'acting_label' => ($userId > 0 && $userId !== $actualUserId) ? (string)($identity['acting_label'] ?? '') : '',
], JSON_UNESCAPED_UNICODE);
$stmt = $conn->prepare("INSERT INTO document_events (document_id, event_type, actor_user_id, actor_section_id, payload_json)
  VALUES (?, 'updated', ?, ?, ?)");
$stmt->bind_param('iiis', $docId, $actualUserId, $mySectionId, $payload);
$stmt->execute();

$mode = $hadExistingDivisionSlip ? 'regenerated' : 'generated';
$message = $hadExistingDivisionSlip
  ? 'Latest division tracking slip generated.'
  : 'Division tracking slip generated.';
echo json_encode([
  'ok' => true,
  'attachment_id' => $attId,
  'stored_name' => $storedName,
  'division_code' => $divisionCode,
  'division_tracking_no' => (string)($trackingRow['tracking_no'] ?? ''),
  'slip_direction' => strtolower($trackingScope),
  'received_by_name' => $receivedBy,
  'received_datetime' => $receivedDT,
  'received_datetime_raw' => $initialReceiveAtRaw,
  'mode' => $mode,
  'message' => $message,
]);
